;;;; kestrel.import.scm - GENERATED BY CHICKEN 4.7.0 -*- Scheme -*-

(eval '(import scheme tcp chicken extras))
(##sys#register-compiled-module
  'kestrel
  (list)
  '((k-connect . kestrel#k-connect)
    (k-disconnect . kestrel#k-disconnect)
    (k-set . kestrel#k-set)
    (k-get . kestrel#k-get)
    (k-begin . kestrel#k-begin)
    (k-commit . kestrel#k-commit)
    (k-rollback . kestrel#k-rollback)
    (k-delete . kestrel#k-delete)
    (k-flush . kestrel#k-flush)
    (k-flush-all . kestrel#k-flush-all)
    (k-version . kestrel#k-version)
    (k-stats . kestrel#k-stats)
    (k-shutdown . kestrel#k-shutdown)
    (k-reload . kestrel#k-reload)
    (k-dump-config . kestrel#k-dump-config)
    (k-dump-stats . kestrel#k-dump-stats))
  (list)
  (list))

;; END OF FILE
